// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219145548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Backend.Models.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ArqueoReal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Diferencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoEsperado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioApertura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCierre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsUnique();

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("Backend.Models.ClienteComprador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientesCompradores");
                });

            modelBuilder.Entity("Backend.Models.ClienteProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAnonimo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoPrestamo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("ZonaId");

                    b.ToTable("ClientesProveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DNI = "00000000",
                            EsAnonimo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Anónimo",
                            SaldoPrestamo = 0m
                        });
                });

            modelBuilder.Entity("Backend.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CajaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DescuentoKg")
                        .HasPrecision(18, 1)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Editada")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsAjustePosterior")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelSecado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroVoucher")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoBruto")
                        .HasPrecision(18, 1)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoNeto")
                        .HasPrecision(18, 1)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPorKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPesado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("ClienteProveedorId");

                    b.HasIndex("NumeroVoucher")
                        .IsUnique();

                    b.HasIndex("ProductoId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Backend.Models.ConfiguracionNegocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContadorVoucher")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("MensajeVoucher")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionNegocio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContadorVoucher = 1,
                            Direccion = "Dirección del negocio",
                            MensajeVoucher = "Gracias por su venta",
                            NombreNegocio = "Comercial Aliaga",
                            RUC = "00000000000",
                            Telefono = "000-000-000"
                        });
                });

            modelBuilder.Entity("Backend.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CajaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAjustePosterior")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoOperacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("Backend.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CajaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAjustePosterior")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoDespues")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("ClienteProveedorId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("Backend.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calidades")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelesSecado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PermiteValdeo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioSugeridoPorKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calidades = "[\"Bajo\",\"Medio\",\"Alto\"]",
                            FechaModificacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelesSecado = "[\"Mote-baba\",\"Húmedo\",\"Estándar\",\"Seco\"]",
                            Nombre = "Café",
                            PermiteValdeo = true,
                            PrecioSugeridoPorKg = 8.50m
                        },
                        new
                        {
                            Id = 2,
                            Calidades = "[\"Normal\",\"Alto\"]",
                            FechaModificacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelesSecado = "[\"Mote-baba\",\"Húmedo\",\"Estándar\",\"Seco\"]",
                            Nombre = "Cacao",
                            PermiteValdeo = true,
                            PrecioSugeridoPorKg = 7.00m
                        },
                        new
                        {
                            Id = 3,
                            Calidades = "[\"Normal\"]",
                            FechaModificacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelesSecado = "[\"Estándar\"]",
                            Nombre = "Maíz",
                            PermiteValdeo = false,
                            PrecioSugeridoPorKg = 2.50m
                        },
                        new
                        {
                            Id = 4,
                            Calidades = "[\"Normal\"]",
                            FechaModificacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelesSecado = "[\"Estándar\"]",
                            Nombre = "Achiote",
                            PermiteValdeo = false,
                            PrecioSugeridoPorKg = 15.00m
                        });
                });

            modelBuilder.Entity("Backend.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CajaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteCompradorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Editada")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsAjustePosterior")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoBruto")
                        .HasPrecision(18, 1)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoNeto")
                        .HasPrecision(18, 1)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPorKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("ClienteCompradorId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Backend.Models.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("Backend.Models.ClienteProveedor", b =>
                {
                    b.HasOne("Backend.Models.Zona", "Zona")
                        .WithMany("Clientes")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Backend.Models.Compra", b =>
                {
                    b.HasOne("Backend.Models.Caja", "Caja")
                        .WithMany("Compras")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ClienteProveedor", "ClienteProveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ClienteProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Producto", "Producto")
                        .WithMany("Compras")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("ClienteProveedor");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend.Models.MovimientoCaja", b =>
                {
                    b.HasOne("Backend.Models.Caja", "Caja")
                        .WithMany("Movimientos")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");
                });

            modelBuilder.Entity("Backend.Models.Prestamo", b =>
                {
                    b.HasOne("Backend.Models.Caja", "Caja")
                        .WithMany("Prestamos")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ClienteProveedor", "ClienteProveedor")
                        .WithMany("Prestamos")
                        .HasForeignKey("ClienteProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("ClienteProveedor");
                });

            modelBuilder.Entity("Backend.Models.Venta", b =>
                {
                    b.HasOne("Backend.Models.Caja", "Caja")
                        .WithMany("Ventas")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ClienteComprador", "ClienteComprador")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteCompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Producto", "Producto")
                        .WithMany("Ventas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("ClienteComprador");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend.Models.Caja", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Movimientos");

                    b.Navigation("Prestamos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Backend.Models.ClienteComprador", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Backend.Models.ClienteProveedor", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("Backend.Models.Producto", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Backend.Models.Zona", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
